server:
  port: 10000

spring:
  application:
    name: spring-ai-alibaba-dashscope-chat-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

# enabled debug log out.
logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug

