server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username:
    password:

  application:
    name: spring-ai-alibaba-graph-sec

  ai:
    openai:
      api-key:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      embedding:
        options:
          model: text-embedding-v1
      chat:
        options:
          model: qwen-max


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
